CREATE TABLE meritlist (
    Srno INT PRIMARY KEY,
    Rollno INT NOT NULL,
    cname VARCHAR(255) NOT NULL,
    Category VARCHAR(50) NOT NULL
);

INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (1, 24133045, 'SAKORKAR SHARANNYA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (2, 24234277, 'DIWAN PRERANA SUNIL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (3, 24182475, 'BYADGI PUSHKAR VINAY', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (4, 24148455, 'MOKSH NIMESH PATEL', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (5, 24153437, 'SAGAR ANKITA ASHOK', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (6, 24109582, 'GUPTA HARSHVARDHAN NAVENDU', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (7, 24180444, 'SAMRUDDHI SUDHAKAR OMBASE', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (8, 24232199, 'SHAH VANSHIKA SACHINKUMAR', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (9, 24188835, 'PRANAV ARORA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (10, 24138003, 'BHURE ARYAN DATTATRAY', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (11, 24122197, 'SONI MADHAV PAWANKUMAR', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (12, 24187372, 'GAWAND PRANAV TANAJI', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (13, 24142634, 'AKSHAT TIKARIA', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (14, 24248558, 'MAHALLE OM VILAS', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (15, 24155293, 'DETHE VED CHANDRASHEKHAR', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (16, 24180600, 'CHINMAY DATTAPRASAD GHATE', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (17, 24284644, 'MAHESHWARY ANANT PRASHANT', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (18, 24247858, 'KALE UDAY GANESH', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (19, 24128986, 'PUJARI VEDANT ASHOK', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (20, 24239161, 'CHOUHAN SUYANSH ARVINDKUMAR', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (21, 24213808, 'SHIMPI MANDAR SANDIP', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (22, 24140600, 'GAIKWAD YUVRAJ YASHWANT', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (23, 24216328, 'ANIRUDH ARVIND MAHAPATRA', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (24, 24143166, 'SAWANT ASHANI SANJAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (25, 24140840, 'RANDIVE RIDDHESH KALIDAS', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (26, 24180556, 'PRAJAPATI JENIL NILESH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (27, 24136441, 'SHREYASH CHANDRA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (28, 24171047, 'MULWANI KRISH NARESH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (29, 24174889, 'GANDHEWAR SWAYAM PARAG', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (30, 24121814, 'UTKARSH GUPTA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (31, 24182021, 'KATDARE KAIVALYA GIRISH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (32, 24140393, 'DALAL JINANSH PUNITKUMAR', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (33, 24146673, 'BHATTAD PRANAV HEMANT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (34, 24138347, 'MORE PRAJWAL PRAMOD', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (35, 24217471, 'WADKILE TUSHAR RAOSAHEB', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (36, 24114837, 'JAMDAR JIBRAN JAVED', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (37, 24138682, 'HAJARNIS INDRANEEL AMOL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (38, 24137219, 'JADHAV MANTHAN BHARAT', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (39, 24270587, 'BADHE VAISHNAVI AMOL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (40, 24240356, 'DESHMUKH YASH SUNIL', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (41, 24274745, 'AGARWAL SIDDHANT LALIT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (42, 24299270, 'NACHAN YASH DNYANDEV', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (43, 24135545, 'SHINDE HARSHWARDHAN YUVARAJ', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (44, 24137438, 'SONAWANE PRACHI PRAMOD', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (45, 24237781, 'ISHAAN SAMEER SARDESHMUKH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (46, 24214884, 'KARAMBALKAR HARSH JITIN', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (47, 24102832, 'MOHIT VIVEK JAIN', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (48, 24199852, 'PASARE SARVESH DATTATRAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (49, 24180314, 'AHUJA KARAN SANJAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (50, 24301030, 'LABHSHETWAR SOHAM LAXMIKANT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (51, 24141393, 'KOTHALKAR YASH ANKUR', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (52, 24115323, 'WAGHMARE JAYESH SANJAY', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (53, 24210161, 'PHARTADE DNYANESHWARI ANIL', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (54, 24133049, 'SAKORKAR SHARANNYA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (55, 24234281, 'DIWAN PRERANA SUNIL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (56, 24182479, 'BYADGI PUSHKAR VINAY', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (57, 24148459, 'MOKSH NIMESH PATEL', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (58, 24153441, 'SAGAR ANKITA ASHOK', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (59, 24109586, 'GUPTA HARSHVARDHAN NAVENDU', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (60, 24180448, 'SAMRUDDHI SUDHAKAR OMBASE', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (61, 24232203, 'SHAH VANSHIKA SACHINKUMAR', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (62, 24188839, 'PRANAV ARORA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (63, 24138007, 'BHURE ARYAN DATTATRAY', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (64, 24122201, 'SONI MADHAV PAWANKUMAR', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (65, 24187376, 'GAWAND PRANAV TANAJI', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (66, 24142638, 'AKSHAT TIKARIA', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (67, 24248562, 'MAHALLE OM VILAS', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (68, 24155297, 'DETHE VED CHANDRASHEKHAR', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (69, 24180604, 'CHINMAY DATTAPRASAD GHATE', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (70, 24284648, 'MAHESHWARY ANANT PRASHANT', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (71, 24247862, 'KALE UDAY GANESH', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (72, 24128990, 'PUJARI VEDANT ASHOK', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (73, 24239165, 'CHOUHAN SUYANSH ARVINDKUMAR', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (74, 24213812, 'SHIMPI MANDAR SANDIP', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (75, 24140604, 'GAIKWAD YUVRAJ YASHWANT', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (76, 24216332, 'ANIRUDH ARVIND MAHAPATRA', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (77, 24143170, 'SAWANT ASHANI SANJAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (78, 24140844, 'RANDIVE RIDDHESH KALIDAS', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (79, 24180560, 'PRAJAPATI JENIL NILESH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (80, 24136445, 'SHREYASH CHANDRA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (81, 24171051, 'MULWANI KRISH NARESH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (82, 24174893, 'GANDHEWAR SWAYAM PARAG', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (83, 24121818, 'UTKARSH GUPTA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (84, 24182025, 'KATDARE KAIVALYA GIRISH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (85, 24140397, 'DALAL JINANSH PUNITKUMAR', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (86, 24146677, 'BHATTAD PRANAV HEMANT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (87, 24138351, 'MORE PRAJWAL PRAMOD', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (88, 24217475, 'WADKILE TUSHAR RAOSAHEB', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (89, 24114841, 'JAMDAR JIBRAN JAVED', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (90, 24138686, 'HAJARNIS INDRANEEL AMOL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (91, 24137223, 'JADHAV MANTHAN BHARAT', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (92, 24270591, 'BADHE VAISHNAVI AMOL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (93, 24240360, 'DESHMUKH YASH SUNIL', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (94, 24274749, 'AGARWAL SIDDHANT LALIT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (95, 24299274, 'NACHAN YASH DNYANDEV', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (96, 24135549, 'SHINDE HARSHWARDHAN YUVARAJ', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (97, 24137442, 'SONAWANE PRACHI PRAMOD', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (98, 24237785, 'ISHAAN SAMEER SARDESHMUKH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (99, 24214888, 'KARAMBALKAR HARSH JITIN', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (100, 24102836, 'MOHIT VIVEK JAIN', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (101, 24199856, 'PASARE SARVESH DATTATRAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (102, 24180318, 'AHUJA KARAN SANJAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (103, 24301034, 'LABHSHETWAR SOHAM LAXMIKANT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (104, 24141397, 'KOTHALKAR YASH ANKUR', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (105, 24115327, 'WAGHMARE JAYESH SANJAY', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (106, 24210165, 'PHARTADE DNYANESHWARI ANIL', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (107, 24133053, 'SAKORKAR SHARANNYA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (108, 24234285, 'DIWAN PRERANA SUNIL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (109, 24182483, 'BYADGI PUSHKAR VINAY', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (110, 24148463, 'MOKSH NIMESH PATEL', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (111, 24153445, 'SAGAR ANKITA ASHOK', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (112, 24109590, 'GUPTA HARSHVARDHAN NAVENDU', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (113, 24180452, 'SAMRUDDHI SUDHAKAR OMBASE', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (114, 24232207, 'SHAH VANSHIKA SACHINKUMAR', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (115, 24188843, 'PRANAV ARORA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (116, 24138011, 'BHURE ARYAN DATTATRAY', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (117, 24122205, 'SONI MADHAV PAWANKUMAR', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (118, 24187380, 'GAWAND PRANAV TANAJI', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (119, 24142642, 'AKSHAT TIKARIA', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (120, 24248566, 'MAHALLE OM VILAS', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (121, 24155301, 'DETHE VED CHANDRASHEKHAR', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (122, 24180608, 'CHINMAY DATTAPRASAD GHATE', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (123, 24284652, 'MAHESHWARY ANANT PRASHANT', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (124, 24247866, 'KALE UDAY GANESH', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (125, 24128994, 'PUJARI VEDANT ASHOK', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (126, 24239169, 'CHOUHAN SUYANSH ARVINDKUMAR', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (127, 24213816, 'SHIMPI MANDAR SANDIP', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (128, 24140608, 'GAIKWAD YUVRAJ YASHWANT', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (129, 24216336, 'ANIRUDH ARVIND MAHAPATRA', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (130, 24143174, 'SAWANT ASHANI SANJAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (131, 24140848, 'RANDIVE RIDDHESH KALIDAS', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (132, 24180564, 'PRAJAPATI JENIL NILESH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (133, 24136449, 'SHREYASH CHANDRA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (134, 24171055, 'MULWANI KRISH NARESH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (135, 24174897, 'GANDHEWAR SWAYAM PARAG', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (136, 24121822, 'UTKARSH GUPTA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (137, 24182029, 'KATDARE KAIVALYA GIRISH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (138, 24140401, 'DALAL JINANSH PUNITKUMAR', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (139, 24146681, 'BHATTAD PRANAV HEMANT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (140, 24138355, 'MORE PRAJWAL PRAMOD', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (141, 24217479, 'WADKILE TUSHAR RAOSAHEB', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (142, 24114845, 'JAMDAR JIBRAN JAVED', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (143, 24138690, 'HAJARNIS INDRANEEL AMOL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (144, 24137227, 'JADHAV MANTHAN BHARAT', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (145, 24270595, 'BADHE VAISHNAVI AMOL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (146, 24240364, 'DESHMUKH YASH SUNIL', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (147, 24274753, 'AGARWAL SIDDHANT LALIT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (148, 24299278, 'NACHAN YASH DNYANDEV', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (149, 24135553, 'SHINDE HARSHWARDHAN YUVARAJ', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (150, 24137446, 'SONAWANE PRACHI PRAMOD', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (151, 24237789, 'ISHAAN SAMEER SARDESHMUKH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (152, 24214892, 'KARAMBALKAR HARSH JITIN', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (153, 24102840, 'MOHIT VIVEK JAIN', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (154, 24199860, 'PASARE SARVESH DATTATRAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (155, 24180322, 'AHUJA KARAN SANJAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (156, 24301038, 'LABHSHETWAR SOHAM LAXMIKANT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (157, 24141401, 'KOTHALKAR YASH ANKUR', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (158, 24115331, 'WAGHMARE JAYESH SANJAY', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (159, 24210169, 'PHARTADE DNYANESHWARI ANIL', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (160, 24133057, 'SAKORKAR SHARANNYA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (161, 24234289, 'DIWAN PRERANA SUNIL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (162, 24182487, 'BYADGI PUSHKAR VINAY', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (163, 24148467, 'MOKSH NIMESH PATEL', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (164, 24153449, 'SAGAR ANKITA ASHOK', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (165, 24109594, 'GUPTA HARSHVARDHAN NAVENDU', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (166, 24180456, 'SAMRUDDHI SUDHAKAR OMBASE', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (167, 24232211, 'SHAH VANSHIKA SACHINKUMAR', 'SC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (168, 24188847, 'PRANAV ARORA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (169, 24138015, 'BHURE ARYAN DATTATRAY', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (170, 24122209, 'SONI MADHAV PAWANKUMAR', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (171, 24187384, 'GAWAND PRANAV TANAJI', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (172, 24142646, 'AKSHAT TIKARIA', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (173, 24248570, 'MAHALLE OM VILAS', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (174, 24155305, 'DETHE VED CHANDRASHEKHAR', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (175, 24180612, 'CHINMAY DATTAPRASAD GHATE', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (176, 24284656, 'MAHESHWARY ANANT PRASHANT', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (177, 24247870, 'KALE UDAY GANESH', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (178, 24128998, 'PUJARI VEDANT ASHOK', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (179, 24239173, 'CHOUHAN SUYANSH ARVINDKUMAR', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (180, 24213820, 'SHIMPI MANDAR SANDIP', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (181, 24140612, 'GAIKWAD YUVRAJ YASHWANT', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (182, 24216340, 'ANIRUDH ARVIND MAHAPATRA', 'ST');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (183, 24143178, 'SAWANT ASHANI SANJAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (184, 24140852, 'RANDIVE RIDDHESH KALIDAS', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (185, 24180568, 'PRAJAPATI JENIL NILESH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (186, 24136453, 'SHREYASH CHANDRA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (187, 24171059, 'MULWANI KRISH NARESH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (188, 24174901, 'GANDHEWAR SWAYAM PARAG', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (189, 24121826, 'UTKARSH GUPTA', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (190, 24182033, 'KATDARE KAIVALYA GIRISH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (191, 24140405, 'DALAL JINANSH PUNITKUMAR', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (192, 24146685, 'BHATTAD PRANAV HEMANT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (193, 24138359, 'MORE PRAJWAL PRAMOD', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (194, 24217483, 'WADKILE TUSHAR RAOSAHEB', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (195, 24114849, 'JAMDAR JIBRAN JAVED', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (196, 24138694, 'HAJARNIS INDRANEEL AMOL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (197, 24137231, 'JADHAV MANTHAN BHARAT', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (198, 24270599, 'BADHE VAISHNAVI AMOL', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (199, 24240368, 'DESHMUKH YASH SUNIL', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (200, 24274757, 'AGARWAL SIDDHANT LALIT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (201, 24299282, 'NACHAN YASH DNYANDEV', 'NTC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (202, 24135557, 'SHINDE HARSHWARDHAN YUVARAJ', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (203, 24137450, 'SONAWANE PRACHI PRAMOD', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (204, 24237793, 'ISHAAN SAMEER SARDESHMUKH', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (205, 24214896, 'KARAMBALKAR HARSH JITIN', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (206, 24102844, 'MOHIT VIVEK JAIN', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (207, 24199864, 'PASARE SARVESH DATTATRAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (208, 24180326, 'AHUJA KARAN SANJAY', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (209, 24301042, 'LABHSHETWAR SOHAM LAXMIKANT', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (210, 24141405, 'KOTHALKAR YASH ANKUR', 'Open');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (211, 24115335, 'WAGHMARE JAYESH SANJAY', 'OBC');
INSERT INTO meritlist (Srno, Rollno, cname, Category) VALUES (212, 24210173, 'PHARTADE DNYANESHWARI ANIL', 'OBC');